services:
    postgres:
        container_name: clicklio_postgres
        image: postgres:alpine
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - network
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DATABASE}
        restart: always

    redis:
        container_name: clicklio_redis
        image: redis:alpine
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
        networks:
            - network
        command: redis-server --requirepass ${REDIS_PASSWORD}
        restart: always

    clicklio:
        container_name: clicklio_backend
        image: mdpahlovi/clicklio:latest
        ports:
            - 5000:5000
            - "44444:44444/udp"
            - "44444:44444/tcp"
        depends_on:
            - postgres
            - redis
        networks:
            - network
        restart: always

volumes:
    postgres_data:
    redis_data:

networks:
    network:
