services:
    postgres:
        container_name: clicklio-postgres
        image: postgres:17-alpine
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        restart: always

    redis:
        container_name: clicklio-redis
        image: redis:8.0.3-alpine
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        restart: always

    redis-insight:
        container_name: clicklio-redis-insight
        image: redis/redisinsight:latest
        ports:
            - 8001:5540
        volumes:
            - redis-insight-data:/data
        depends_on:
            - redis
        restart: always

volumes:
    postgres-data:
    redis-data:
    redis-insight-data:
