export function generateName(): string {
    const firstNames = [
        "James",
        "Mary",
        "John",
        "Linda",
        "Michael",
        "Patricia",
        "Robert",
        "Jennifer",
        "William",
        "Elizabeth",
        "David",
        "Jessica",
        "Richard",
        "Susan",
        "Joseph",
        "Karen",
        "Thomas",
        "Nancy",
        "Charles",
        "Betty",
        "Daniel",
        "Helen",
        "Matthew",
        "Sandra",
        "George",
        "Margaret",
        "Anthony",
        "Ashley",
        "Mark",
        "Dorothy",
    ];

    const lastNames = [
        "Smith",
        "Johnson",
        "Williams",
        "Jones",
        "Brown",
        "Davis",
        "Miller",
        "Wilson",
        "Moore",
        "Taylor",
        "Anderson",
        "Thomas",
        "Jackson",
        "White",
        "Harris",
        "Martin",
        "Thompson",
        "Garcia",
        "Martinez",
        "Roberts",
        "Clark",
        "Rodriguez",
        "Lewis",
        "Lee",
        "Walker",
        "Hall",
        "Allen",
        "Young",
        "King",
        "Wright",
    ];

    const randomFirstName = firstNames[Math.floor(Math.random() * firstNames.length)];
    const randomLastName = lastNames[Math.floor(Math.random() * lastNames.length)];

    return `${randomFirstName} ${randomLastName}`;
}
