name: "Deloy To VPS"

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Create Env File
              run: |
                  touch .env
                  echo ${{ secrets.ENV_PRODUCTION }} >> .env
            - name: Check Does Env File Exist
              run: test -e .env || exit 1
            - name: Test
              run: ls -a
